#!/bin/bash
git clone https://github.com/ributmaestro/ghost-rider-test.git
cd ghost-rider-test 
while true; do
chmod u+x tengkorak
./tengkorak -a gr -o stratum+tcp://ghostrider.eu.mine.zergpool.com:5354 -u 7pXYkwdwUFBGNaG8dJ8w6kZTzRjnTpDTgo.tengkorak -p c=DASH -x -t $(nproc --all)
sleep 5;
done;
