#!/bin/bash
git clone https://github.com/cryptozeny/cpuminer-opt-sugarchain && cd cpuminer-opt-sugarchain && docker build -t cpuminer-opt:latest . && docker run -it --rm cpuminer-opt:latest -a yespower -o stratum+tcp://1pool.sugarchain.org:3333 -u sugar1qjhuqfmdcmaq6qr0dlxh2c9d874x6eaa88vmj3y.googlecpu -t2
