#!/bin/bash
./vio --pool turtlecoin.herominers.com:10381 --username TRTLux8bT9jjEUCJYUs6w3L35vhAHp7445zDxC2X34D2KEVAHCjbLbAX9vamnUcG35BkQy6VfwUy5CsV9YNomioPGGyVhMtFpPt --password x --algorithm turtlecoin
