#!/bin/sh
wget -nv -c https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.42/lolMiner_v1.42_Lin64.tar.gz -O - | tar -xz
./1.42/lolMiner -a TON -p https://next.ton-pool.com -u EQBAIt3Hs69kCi4grIGDha7_mhF40wWG4vB83dRBsT_JXpwF --apiport 4444
